name: Greeting Workflow

on:
  push:
    branches:
      - main  

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: Accessing the variable
        run: echo "${{ vars.USERNAME }}" 

      - name: Say Hello
        run: echo "Hello $USERNAME!"
